"use client";

import { useState } from "react";
import { ResearchReport as Report } from "@/lib/types";
import SourceCard from "./SourceCard";

interface ResearchReportProps {
  report: Report;
  onReset: () => void;
}

function ConfidenceBadge({ level }: { level: Report["confidence"] }) {
  const styles = {
    high: "bg-emerald-500/15 text-emerald-400 border-emerald-500/20",
    medium: "bg-amber-500/15 text-amber-400 border-amber-500/20",
    low: "bg-red-500/15 text-red-400 border-red-500/20",
  };
  const icons = { high: "✓", medium: "~", low: "!" };

  return (
    <span
      className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full border text-sm font-semibold ${styles[level]}`}
    >
      <span>{icons[level]}</span>
      {level.charAt(0).toUpperCase() + level.slice(1)} Confidence
    </span>
  );
}

function Section({
  title,
  icon,
  children,
}: {
  title: string;
  icon: string;
  children: React.ReactNode;
}) {
  return (
    <section className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
      <h2 className="flex items-center gap-2 text-lg font-semibold text-white mb-4">
        <span>{icon}</span>
        {title}
      </h2>
      {children}
    </section>
  );
}

export default function ResearchReport({ report, onReset }: ResearchReportProps) {
  const [copied, setCopied] = useState(false);

  function buildMarkdown(): string {
    const lines: string[] = [];

    lines.push(`# Research Report: ${report.topic}`, "");
    lines.push("## Executive Summary", "", report.summary, "");

    if (report.keyFindings.length > 0) {
      lines.push("## Key Findings", "");
      report.keyFindings.forEach((f) => lines.push(`- ${f}`));
      lines.push("");
    }

    if (report.sources.length > 0) {
      lines.push("## Source Breakdown", "");
      report.sources.forEach((s, i) => {
        lines.push(`### ${i + 1}. ${s.title}`);
        lines.push(`- **URL:** ${s.url}`);
        if (s.publishedDate) lines.push(`- **Date:** ${s.publishedDate}`);
        if (s.author) lines.push(`- **Author:** ${s.author}`);
        lines.push(`- **Relevance:** ${s.relevanceScore}/10`);
        lines.push(`- **Summary:** ${s.summary}`);
        lines.push("");
      });
    }

    if (report.timeline.length > 0) {
      lines.push("## Timeline", "");
      report.timeline.forEach((e) => {
        lines.push(`- **${e.date}** — ${e.event}`);
      });
      lines.push("");
    }

    if (report.conflicts.length > 0) {
      lines.push("## Conflicting Information", "");
      report.conflicts.forEach((c) => {
        lines.push(`**${c.claim}**`);
        c.perspectives.forEach((p) => lines.push(`  - ${p.source}: ${p.position}`));
      });
      lines.push("");
    }

    if (report.opportunities.length > 0) {
      lines.push("## Opportunities / Insights", "");
      report.opportunities.forEach((o) => lines.push(`- ${o}`));
      lines.push("");
    }

    lines.push("## Final Verdict", "", report.finalVerdict, "");
    lines.push(`---`);
    lines.push(`*Confidence: ${report.confidence} | Generated by Research Agent*`);

    return lines.join("\n");
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(buildMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleExport() {
    const md = buildMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-${report.topic.slice(0, 40).replace(/\s+/g, "-").toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const relevantSources = report.sources.filter((s) => s.relevanceScore >= 3);
  const lowSources = report.sources.filter((s) => s.relevanceScore < 3);

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6 pb-16">
      {/* Report Header */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pt-8">
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest text-zinc-500 mb-1">
            Research Report
          </p>
          <h1 className="text-2xl sm:text-3xl font-bold text-white leading-tight">
            {report.topic}
          </h1>
          <div className="flex items-center gap-3 mt-2">
            <ConfidenceBadge level={report.confidence} />
            <span className="text-xs text-zinc-500">
              {relevantSources.length} source{relevantSources.length !== 1 ? "s" : ""} analyzed
            </span>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-2 flex-shrink-0">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-sm text-zinc-300 hover:text-white border border-zinc-700 transition-all"
          >
            {copied ? (
              <>
                <svg className="w-4 h-4 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy Report
              </>
            )}
          </button>

          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-sm text-zinc-300 hover:text-white border border-zinc-700 transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Export .md
          </button>

          <button
            onClick={onReset}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-sm text-zinc-300 hover:text-white border border-zinc-700 transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            New Search
          </button>
        </div>
      </div>

      {/* Executive Summary */}
      <Section title="Executive Summary" icon="📋">
        <p className="text-zinc-300 leading-relaxed">{report.summary}</p>
      </Section>

      {/* Key Findings */}
      {report.keyFindings.length > 0 && (
        <Section title="Key Findings" icon="🔑">
          <ul className="space-y-2.5">
            {report.keyFindings.map((finding, i) => (
              <li key={i} className="flex items-start gap-3 text-zinc-300">
                <span className="flex-shrink-0 mt-0.5 w-5 h-5 rounded-full bg-violet-500/20 border border-violet-500/30 flex items-center justify-center text-xs font-bold text-violet-400">
                  {i + 1}
                </span>
                <span className="leading-relaxed">{finding}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Timeline */}
      {report.timeline.length > 0 && (
        <Section title="Timeline" icon="📅">
          <div className="relative pl-6 border-l border-zinc-700 space-y-4">
            {report.timeline.map((event, i) => (
              <div key={i} className="relative">
                <div className="absolute -left-[1.65rem] mt-1 w-3 h-3 rounded-full bg-violet-500 border-2 border-zinc-900" />
                <p className="text-xs font-semibold text-violet-400 mb-0.5">
                  {event.date}
                </p>
                <p className="text-sm text-zinc-300">{event.event}</p>
                {event.source && (
                  <a
                    href={event.source}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-zinc-600 hover:text-zinc-400 transition-colors"
                  >
                    {event.source.replace(/^https?:\/\//, "").slice(0, 50)}
                  </a>
                )}
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Sources */}
      {relevantSources.length > 0 && (
        <Section title={`Sources (${relevantSources.length})`} icon="🔗">
          <div className="space-y-4">
            {relevantSources.map((source, i) => (
              <SourceCard key={source.url + i} source={source} index={i} />
            ))}
          </div>
          {lowSources.length > 0 && (
            <p className="mt-3 text-xs text-zinc-600">
              {lowSources.length} low-relevance source{lowSources.length !== 1 ? "s" : ""} were found but excluded from the report.
            </p>
          )}
        </Section>
      )}

      {/* Conflicts */}
      {report.conflicts.length > 0 && (
        <Section title="Conflicting Information" icon="⚠️">
          <div className="space-y-4">
            {report.conflicts.map((conflict, i) => (
              <div
                key={i}
                className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-4"
              >
                <p className="text-sm font-semibold text-amber-400 mb-2">
                  {conflict.claim}
                </p>
                <div className="space-y-1.5">
                  {conflict.perspectives.map((p, j) => (
                    <div key={j} className="flex gap-2 text-sm">
                      <span className="flex-shrink-0 text-zinc-500">
                        {p.source.replace(/^https?:\/\//, "").slice(0, 30)}:
                      </span>
                      <span className="text-zinc-400">{p.position}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Opportunities */}
      {report.opportunities.length > 0 && (
        <Section title="Opportunities & Insights" icon="💡">
          <ul className="space-y-2.5">
            {report.opportunities.map((opp, i) => (
              <li key={i} className="flex items-start gap-3 text-zinc-300">
                <span className="flex-shrink-0 text-cyan-500 mt-0.5">→</span>
                <span className="leading-relaxed">{opp}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Final Verdict */}
      <Section title="Final Verdict" icon="🏁">
        <div className="flex items-start gap-4">
          <div className="flex-1">
            <p className="text-zinc-200 leading-relaxed font-medium">
              {report.finalVerdict}
            </p>
          </div>
        </div>
        <div className="mt-4 pt-4 border-t border-zinc-800 flex items-center justify-between">
          <ConfidenceBadge level={report.confidence} />
          <p className="text-xs text-zinc-600">
            Based on {relevantSources.length} source{relevantSources.length !== 1 ? "s" : ""}
          </p>
        </div>
      </Section>
    </div>
  );
}
