"use client";

import { useState } from "react";
import type { ResearchReport as Report } from "@/types/research";
import SourceCard from "./SourceCard";

interface ResearchReportProps {
  report: Report;
  onNewSearch: () => void;
}

function ConfidenceBadge({ confidence }: { confidence: string }) {
  const config = {
    high: { label: "High Confidence", color: "var(--green)", bg: "rgba(16,185,129,0.1)", icon: "✓" },
    medium: { label: "Medium Confidence", color: "var(--warning)", bg: "rgba(245,158,11,0.1)", icon: "~" },
    low: { label: "Low Confidence", color: "var(--danger)", bg: "rgba(239,68,68,0.1)", icon: "!" },
  }[confidence as "high" | "medium" | "low"] ?? {
    label: confidence,
    color: "var(--text-muted)",
    bg: "var(--border)",
    icon: "?",
  };

  return (
    <span
      className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold"
      style={{ background: config.bg, color: config.color }}
    >
      <span>{config.icon}</span>
      {config.label}
    </span>
  );
}

function SectionHeader({ icon, title }: { icon: string; title: string }) {
  return (
    <div className="flex items-center gap-3 mb-4">
      <span className="text-xl">{icon}</span>
      <h2 className="text-lg font-bold" style={{ color: "#fff" }}>
        {title}
      </h2>
    </div>
  );
}

function Section({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={`rounded-2xl border p-6 ${className}`}
      style={{ background: "var(--bg-card)", borderColor: "var(--border)" }}
    >
      {children}
    </div>
  );
}

function buildMarkdown(report: Report): string {
  const lines: string[] = [];
  lines.push(`# Research Report: ${report.topic}`, "");
  lines.push(`**Confidence:** ${report.confidence}`, "");
  lines.push("## Executive Summary", "", report.summary, "");

  if (report.keyFindings.length > 0) {
    lines.push("## Key Findings", "");
    report.keyFindings.forEach((f) => lines.push(`- ${f}`));
    lines.push("");
  }

  if (report.sources.length > 0) {
    lines.push("## Source Breakdown", "");
    report.sources.forEach((s, i) => {
      lines.push(
        `### ${i + 1}. ${s.title}`,
        `- **URL:** ${s.url}`,
        `- **Source:** ${s.source}`,
        s.author ? `- **Author:** ${s.author}` : "",
        s.publishedDate ? `- **Date:** ${s.publishedDate}` : "",
        `- **Relevance:** ${s.relevanceScore}/10`,
        "",
        s.summary,
        ""
      );
      if (s.mainClaims.length > 0) {
        lines.push("**Key claims:**");
        s.mainClaims.forEach((c) => lines.push(`- ${c}`));
        lines.push("");
      }
    });
  }

  if (report.timeline.length > 0) {
    lines.push("## Timeline", "");
    report.timeline.forEach((t) => {
      lines.push(`- **${t.date}** — ${t.event}${t.source ? ` ([source](${t.source}))` : ""}`);
    });
    lines.push("");
  }

  if (report.conflicts.length > 0) {
    lines.push("## Conflicting Information", "");
    report.conflicts.forEach((c) => lines.push(`- ${c}`));
    lines.push("");
  }

  if (report.opportunities.length > 0) {
    lines.push("## Opportunities / Insights", "");
    report.opportunities.forEach((o) => lines.push(`- ${o}`));
    lines.push("");
  }

  lines.push("## Final Verdict", "", report.finalVerdict, "");
  lines.push(
    "---",
    `*Generated by Research Agent · ${new Date().toLocaleDateString()}*`
  );

  return lines.filter((l) => l !== undefined).join("\n");
}

export default function ResearchReport({ report, onNewSearch }: ResearchReportProps) {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"report" | "sources">("report");

  const markdown = buildMarkdown(report);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleExport = () => {
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-${report.topic.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-5xl mx-auto mt-8 space-y-6 fade-in">
      {/* Header bar */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <p className="text-xs mb-1" style={{ color: "var(--text-muted)" }}>
            Research complete
          </p>
          <h1 className="text-2xl font-bold" style={{ color: "#fff" }}>
            {report.topic}
          </h1>
          <div className="mt-2 flex items-center gap-3">
            <ConfidenceBadge confidence={report.confidence} />
            <span className="text-xs" style={{ color: "var(--text-muted)" }}>
              {report.sources.length} sources analyzed
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={onNewSearch}
            className="px-4 py-2 rounded-xl text-sm border transition-colors hover:border-indigo-500"
            style={{
              background: "var(--bg-card)",
              borderColor: "var(--border)",
              color: "var(--text-secondary)",
            }}
          >
            New search
          </button>
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl text-sm flex items-center gap-2 border transition-all duration-200"
            style={{
              background: copied ? "rgba(16,185,129,0.1)" : "var(--bg-card)",
              borderColor: copied ? "var(--green)" : "var(--border)",
              color: copied ? "var(--green)" : "var(--text-secondary)",
            }}
          >
            {copied ? (
              <>
                <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                </svg>
                Copy Report
              </>
            )}
          </button>
          <button
            onClick={handleExport}
            className="px-4 py-2 rounded-xl text-sm flex items-center gap-2 transition-all duration-200"
            style={{
              background: "linear-gradient(135deg, #6366f1, #818cf8)",
              color: "#fff",
              boxShadow: "0 4px 12px rgba(99,102,241,0.25)",
            }}
          >
            <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Export .md
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div
        className="flex gap-1 p-1 rounded-xl border w-fit"
        style={{ background: "var(--bg-secondary)", borderColor: "var(--border)" }}
      >
        {(["report", "sources"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className="px-5 py-2 rounded-lg text-sm font-medium transition-all duration-200 capitalize"
            style={{
              background: activeTab === tab ? "var(--bg-card)" : "transparent",
              color: activeTab === tab ? "var(--text-primary)" : "var(--text-muted)",
              boxShadow: activeTab === tab ? "0 1px 4px rgba(0,0,0,0.3)" : "none",
            }}
          >
            {tab === "sources" ? `Sources (${report.sources.length})` : tab}
          </button>
        ))}
      </div>

      {activeTab === "report" && (
        <div className="space-y-5">
          {/* Executive Summary */}
          <Section>
            <SectionHeader icon="📋" title="Executive Summary" />
            <p className="text-base leading-relaxed" style={{ color: "var(--text-secondary)" }}>
              {report.summary}
            </p>
          </Section>

          {/* Key Findings */}
          {report.keyFindings.length > 0 && (
            <Section>
              <SectionHeader icon="🔑" title="Key Findings" />
              <ul className="space-y-2.5">
                {report.keyFindings.map((finding, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      className="flex-shrink-0 mt-1 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold"
                      style={{ background: "var(--accent-dim)", color: "var(--accent)" }}
                    >
                      {i + 1}
                    </span>
                    <span className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                      {finding}
                    </span>
                  </li>
                ))}
              </ul>
            </Section>
          )}

          {/* Timeline */}
          {report.timeline.length > 0 && (
            <Section>
              <SectionHeader icon="📅" title="Timeline" />
              <div className="relative pl-4">
                <div
                  className="absolute left-0 top-2 bottom-2 w-0.5 rounded-full"
                  style={{ background: "var(--border)" }}
                />
                <div className="space-y-4">
                  {report.timeline.map((event, i) => (
                    <div key={i} className="relative pl-6">
                      <div
                        className="absolute left-0 top-1.5 w-3 h-3 rounded-full border-2 -translate-x-1/2"
                        style={{
                          background: "var(--accent)",
                          borderColor: "var(--bg-card)",
                          left: "-1px",
                        }}
                      />
                      <p className="text-xs mb-0.5 font-semibold" style={{ color: "var(--accent-hover)" }}>
                        {event.date}
                      </p>
                      <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                        {event.event}
                      </p>
                      {event.source && (
                        <a
                          href={event.source}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs mt-0.5 inline-flex items-center gap-1 hover:underline"
                          style={{ color: "var(--text-muted)" }}
                        >
                          Source
                          <svg width="9" height="9" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                          </svg>
                        </a>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </Section>
          )}

          {/* Two-column: Conflicts + Opportunities */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {/* Conflicting Information */}
            {report.conflicts.length > 0 && (
              <Section>
                <SectionHeader icon="⚠️" title="Conflicting Info" />
                <ul className="space-y-2">
                  {report.conflicts.map((conflict, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-2 text-sm p-3 rounded-lg"
                      style={{ background: "rgba(239,68,68,0.06)", color: "var(--text-secondary)" }}
                    >
                      <span className="flex-shrink-0 mt-0.5 text-red-400">⚡</span>
                      {conflict}
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            {/* Opportunities / Insights */}
            {report.opportunities.length > 0 && (
              <Section>
                <SectionHeader icon="💡" title="Opportunities / Insights" />
                <ul className="space-y-2">
                  {report.opportunities.map((opp, i) => (
                    <li
                      key={i}
                      className="flex items-start gap-2 text-sm p-3 rounded-lg"
                      style={{ background: "rgba(99,102,241,0.06)", color: "var(--text-secondary)" }}
                    >
                      <span className="flex-shrink-0 mt-0.5" style={{ color: "var(--accent)" }}>→</span>
                      {opp}
                    </li>
                  ))}
                </ul>
              </Section>
            )}
          </div>

          {/* Final Verdict */}
          <div
            className="rounded-2xl border p-6"
            style={{
              background: "linear-gradient(135deg, rgba(99,102,241,0.08) 0%, rgba(167,139,250,0.05) 100%)",
              borderColor: "rgba(99,102,241,0.3)",
            }}
          >
            <SectionHeader icon="🏁" title="Final Verdict" />
            <p className="text-base leading-relaxed font-medium" style={{ color: "var(--text-primary)" }}>
              {report.finalVerdict}
            </p>
            <div className="mt-4">
              <ConfidenceBadge confidence={report.confidence} />
            </div>
          </div>
        </div>
      )}

      {activeTab === "sources" && (
        <div>
          {report.sources.length === 0 ? (
            <Section>
              <p className="text-sm text-center py-8" style={{ color: "var(--text-muted)" }}>
                No sources were extracted for this research.
              </p>
            </Section>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {report.sources.map((source, i) => (
                <SourceCard key={i} source={source} index={i} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
