export const ITEMS = {
  longbow: { id: 'longbow', name: 'Yew Longbow', icon: '🏹', price: 45, type: 'weapon', rarity: 'uncommon' },
  arrows: { id: 'arrows', name: 'Arrow Bundle', icon: '➹', price: 12, type: 'ammo', rarity: 'common' },
  dagger: { id: 'dagger', name: 'Hunting Dagger', icon: '🗡️', price: 18, type: 'weapon', rarity: 'common' },
  sword: { id: 'sword', name: 'Merry Blade', icon: '⚔️', price: 65, type: 'weapon', rarity: 'rare' },
  leather_armor: { id: 'leather_armor', name: 'Leather Jerkin', icon: '🛡️', price: 35, type: 'armor', rarity: 'uncommon' },
  hood_cloak: { id: 'hood_cloak', name: 'Forest Cloak', icon: '🧥', price: 28, type: 'armor', rarity: 'uncommon' },
  health_potion: { id: 'health_potion', name: 'Healing Draught', icon: '🧪', price: 15, type: 'consumable', rarity: 'common' },
  bread: { id: 'bread', name: 'Village Loaf', icon: '🍞', price: 5, type: 'food', rarity: 'common' },
  ale: { id: 'ale', name: 'Sherwood Ale', icon: '🍺', price: 8, type: 'food', rarity: 'common' },
  gold_ring: { id: 'gold_ring', name: 'Noble\'s Ring', icon: '💍', price: 120, type: 'treasure', rarity: 'rare' },
  herbs: { id: 'herbs', name: 'Forest Herbs', icon: '🌿', price: 10, type: 'material', rarity: 'common' },
  iron_ingot: { id: 'iron_ingot', name: 'Iron Ingot', icon: '🔩', price: 22, type: 'material', rarity: 'common' },
  horseshoe: { id: 'horseshoe', name: 'Lucky Horseshoe', icon: '🐴', price: 14, type: 'misc', rarity: 'common' },
  map: { id: 'map', name: 'Forest Map', icon: '🗺️', price: 20, type: 'misc', rarity: 'uncommon' },
  quiver: { id: 'quiver', name: 'Leather Quiver', icon: '🎯', price: 16, type: 'accessory', rarity: 'common' },
  emerald: { id: 'emerald', name: 'Forest Emerald', icon: '💎', price: 200, type: 'treasure', rarity: 'legendary' },
  roasted_meat: { id: 'roasted_meat', name: 'Roasted Venison', icon: '🍖', price: 12, type: 'food', rarity: 'common' },
  torch: { id: 'torch', name: 'Pine Torch', icon: '🔥', price: 6, type: 'misc', rarity: 'common' },
  rope: { id: 'rope', name: 'Hemp Rope', icon: '🪢', price: 9, type: 'material', rarity: 'common' },
  lockpick: { id: 'lockpick', name: 'Lockpick Set', icon: '🔑', price: 25, type: 'tool', rarity: 'uncommon' },
};

export const SHOPS = [
  {
    id: 'archery',
    name: "Will Scarlet's Archery",
    sign: '🏹 ARCHERY',
    color: 0x2d5a3d,
    position: { x: -22, z: -18 },
    rotation: Math.PI / 4,
    merchant: { name: 'Will Scarlet', icon: '🏹' },
    stock: ['longbow', 'arrows', 'quiver', 'hood_cloak', 'map'],
    npcPosition: { x: -20, z: -16 },
  },
  {
    id: 'blacksmith',
    name: "Little John's Forge",
    sign: '⚒️ FORGE',
    color: 0x4a3728,
    position: { x: 22, z: -18 },
    rotation: -Math.PI / 4,
    merchant: { name: 'Little John', icon: '⚒️' },
    stock: ['sword', 'dagger', 'iron_ingot', 'horseshoe', 'leather_armor'],
    npcPosition: { x: 20, z: -16 },
  },
  {
    id: 'tavern',
    name: 'The Merry Outlaw Tavern',
    sign: '🍺 TAVERN',
    color: 0x5c3d2e,
    position: { x: -22, z: 18 },
    rotation: -Math.PI / 4,
    merchant: { name: 'Maid Marian', icon: '🍺' },
    stock: ['ale', 'bread', 'roasted_meat', 'health_potion', 'herbs'],
    npcPosition: { x: -20, z: 16 },
  },
  {
    id: 'market',
    name: 'Sherwood Market Stall',
    sign: '🛒 MARKET',
    color: 0x6b5b3a,
    position: { x: 22, z: 18 },
    rotation: Math.PI / 4,
    merchant: { name: 'Friar Tuck', icon: '🛒' },
    stock: ['herbs', 'rope', 'torch', 'bread', 'lockpick', 'gold_ring'],
    npcPosition: { x: 20, z: 16 },
  },
  {
    id: 'treasury',
    name: "Robin's Treasury",
    sign: '💰 TRADE HALL',
    color: 0x3d4a5c,
    position: { x: 0, z: -30 },
    rotation: 0,
    merchant: { name: 'Robin Hood', icon: '🏹' },
    stock: ['emerald', 'gold_ring', 'map', 'hood_cloak', 'sword'],
    npcPosition: { x: 0, z: -27 },
  },
];

export const TRAVELERS = [
  { name: 'Wandering Merchant', icon: '🧳', wants: ['herbs', 'iron_ingot'], offers: ['health_potion', 'map'], path: [{ x: -8, z: 0 }, { x: 8, z: 0 }, { x: 8, z: 8 }, { x: -8, z: 8 }] },
  { name: 'Forest Ranger', icon: '🌲', wants: ['arrows', 'torch'], offers: ['herbs', 'quiver'], path: [{ x: 0, z: 10 }, { x: 12, z: 5 }, { x: -5, z: -10 }, { x: 0, z: 10 }] },
  { name: 'Noble Traveler', icon: '👑', wants: ['emerald', 'gold_ring'], offers: ['sword', 'leather_armor'], path: [{ x: 15, z: -5 }, { x: -10, z: 5 }, { x: 5, z: 15 }, { x: 15, z: -5 }] },
];
